---
title: "About me"
--- 
The purpose of this website is to serve as an extension of my resumé and to host [my Portfolio](http://sdhector.github.io/portfolio.html), which contains a series of work Samples where I showcase my theoretical and practical knowledge by descrbing my approach to solving a number of problems using R.  

As for myself, my name is Hector Sanchez and I come from the the Dominican Republic. I hold a Bachelor's degree in Marketing, a Specialization of Statistics Applied to Business and a Master of Science in Economics from the University of Konstanz, Germany. 

I am a Quantitative Market Researcher with experience designing and executing numerous projects for clients in the Dominican Republic. I can advise on the proper methodology to achieve the client's objectives, design the sampling methodology, the questionnaire or other data collection method, analyze the data and communicate the findings effectively. 

Aside of primary data, I am also experienced conducting research using secondary data - most notably using Econometric models for cross-sectional, time-series, and Panel Data. 

The fields where I'm interested in conducting research are the following: 

  - Marketing Research
  - Operations Research
  - Economic Research
  - Finance
  - Social Research

Given my career path, I can also see myfself in fields such as Quantitative Risk Management, Financial Econometrics, Macroeconomic Forecasting, Business Intelligence, Data Analysis, Data Mining, or Data Science. That last one with an emphasis on the research aspect and less so with the implementation since I do not have the programming skills to do that. 


