---
title: "Hector Sanchez's Personal Website"
---

### Hello! Welcome to my personal website. 

#### Why a website? 

The **current** purpose of this website is to show potential employers a more extensive view of my professional career so far, so they can determine if I could help them achieve their goals effectively and efficiently. This is something that cannot be done with a simple CV, not even with a cover letter. That's left for the interview, along with appearing confident, selling yourself and making a connection. Instead, I hope that my future employer shares my belief of entering the interview knowing I can do what's needed, and that the goal is to test if our personalities and philosophies are such that we can get along. 

To help achieve this, here you'll find more detailed descriptions of the [roles I have performed as in the past](http://sdhector.github.io/roles.html/), as well as of the [projects I have done](http://sdhector.github.io/projects_completed.html/) in those roles. I also show you the projects I'm [currently working on](http://sdhector.github.io/roles.html/) in order to learn, practice and hone my skills. You can also see the things i'm curious by looking at the [projects i'm considering doing in the future](http://sdhector.github.io/future_projects.html/).

Similarly, I share here [my philosophy](http://sdhector.github.io/myphilosophy.html/), where I describe the way I approach my job and the reasonsing behind it. I have also included some [blog entries](http://sdhector.github.io/opinions.html/) where you can see the end product of my beliefs in the form of opinion articles. 

Let's face it. If i'm applying to your vacant position, then I most likely want to join. And if you read this and still take me in for an interview, then you also are likely convinced of the match. The last mile is achieved just in having a nice, fun, and insightful conversation where we can both come out smiling, no matter the final outcome. 

#### What else can you find here? 

I am currently in the process of populating the website. However, I did start one project already where I explore [the drivers of Customer Satisfaction Indices](http://sdhector.github.io/satisfaction.html/). This will take a while to complete, but hopefully it will help shed some light into what I have done and their implications for you. 

