---
title: "My opinions"
---
A list of articles describing my opinion on several topics. 

### On how to achieve causality:
For a long time I had been searching the holly grail. I was confused for quite a while, and "Granger Causality" did not help in clearning things up. In this article I explain how Causality is nothing else but the result of a Scientific Theory that is supported by evidence. 

### What do Data Scientist and Rappers have in common? 
I have written a version of this article in Spanish because it is funnier and more relatable for Dominicans. Instead of Rappers, I actually mean "Dembowseros". In short, this kind of rappers shows the ability of people to teach themselves how to do certain things and, in the right conditions, how this can lead to profitable trades. Using online tutorials and perhaps pirated software, Dominican DJs started playing around with making "beats". Some eventually made it to working for Reggaeton stars like Wisin y Yandel, and those who came after eventually paired with rappers who had catchy lyrics. Along with catchy upbeat "beats", they develop the "Dembow" genre which has overtaken the Dominican music industry for several years now. The same thing happened in Puerto Rico previously with reggaeton of course, but the message is that if people do something they like, they will work harder than "rational" and perhaps make great progress at it. 

### The CPI is, by definition, wrong: 
I am arrogant, in case you couldn't tell by my website. However, I admit when I'm wrong. I don't understand how economists still argue with people when they say that the IPC, and more specifically inflation, does not correspond to their experiences. The IPC is literally an average. It is not mean to properly represent any one person's experiences. Furthermore, the whole concept of measuring the prices and collapsing them into a single index comes from the assumption of the representative household in Macroeconomics. This assumption is necessary not because it describes reality, but because it allows economists to aggregate preferences that have otherwise been shown to be impossible to aggregate. The only way an IPC could be statistically descriptive of people is if it represented a homogenoeously distributed population. That's because, ultimately, how someone perceives changes in prices depends on the specific vector that represents their demand for the various goods and services they consume. You could find people who are sufficiently similar, but that in no way would leave you with one aggregate Consumer Price Index. 

### My Life with R
I am very new to R. However, the fact that I have a website, albeit static, is a major breakthrough. I can write a report and embed code in it. All from the comfort of one place. I can even do Big Data Analysis with Hadoop. Yes, Python might offer the same and maybe even more, but I'm not going that way. Economists already don't need the number of things R provides. The fact that it's putting them together so neatly however, makes them hard not to try. 

### On the A-Morality of markets
Nowadays I have become more politically involved. This starts with discussions, and eventually slips into my thoughts. I came across a very nice video of Friederich Hayek arguing that no one can say that the result of a market is inmoral because the market is not an entity. It cannot hold blame. Ultimately, it is the result of uncountable interactions that lead to any given result. While I am not a socialist, I also don't think that markets are the only way to go. I believe that proponents of markets, especially those who are not economists, find the fact that no one is at fault for poverty soothing. It apeaces their minds. When a socialist proposes something with all the intention to do good, but fails; they are hald accountable. When the markets are left to do the job, even if the same result were achieved, i.e. a person losing their savings because their business didn't go well, no one is said to be at fault. It was the forces of the market, a better competitor, globalization, etc. 
