---
title: "Projects currently under development"
---
A list of articles discussing projects I am currently working on. 

### Churn Prediction:
This is a very famous problem in Machine Learning. In this article I explain how the probability that a subscriber would cancel their service in a specified ammount of time was estimated using a Logistic Regression. I explain how the "under-sampling" technique was used to solve the class-imbalance problem, the cut-off point used for classification purposes, the uses of the forecasted likelihood - indeed, the risk - of churning,  how to evaluate the accuracy of the model, and how to use out of sample validation to evaluate the performance of the model. I also discuss the "econometric" vs "machine learning" reasoning when faced with problems like this, and how validation only makes sense for Machine Learning, and not for Econometrics. 

### Choice-based Conjoint Analysis: 
In this article I explain how to measure consumer choices with choice-based conjoint analysis. The technique is based on the microeconomic rational choice theory, except that the sources of utility are not goods, but the characteristics of those goods. This allows for the comparison of goods that, for normal economic analysis, would be considered perfect substitutes. The analysis requires constructing a fractional-factorial experimental design, which allows one to be reasonably sure that the all the task choices are considered and there aren't any uncontrolled for effects. 

### Measuring Brand Equity with Conjoint Analysis: 
Using choice-based conjoint analysis, by including the brand among the utility generating characteristics of the goods, it is possible to isolate the "ammount of utility" that the brand generates after controlling for other aspects of the product. 

### Attitudes as determinants of Choice in a Conjoint Experiment: 
In this article I discuss the possibility of using liker-scale measured attitudes regarding the different brands, in order to explain choice in a CBCE. The general idea is that, while the attitudes do not themselves reflect on the specific choices, they might influence the preferences themselves; meaning, how much people care about brand vs price, for example. 

### Marketing Mix Model:
The effect of marketing efforts on sales is an important concern. At the very least, it provides information on how effective advertising is. This can bring good or bad news, but in order to improve one must first measure. This project discusses the very basic idea first, which is a linear model explaining sales as a consequence of advertising. In practice, however, several other variables might influence sales. Furthermore, the relationship might not be direct in time, but lagged and cumulative. I discuss how to incorporate Vector AutoRegressive concepts like Impulse Response functions to identify the fact that advertising today has a diminishing effect on future sales. 

### [The drivers of Customer Satisfaction Indices](http://sdhector.github.io/satisfaction.html/)
In this article I discuss the theory of Customer Satisfaction and explain under what conditions it holds, and what are the implications when it does. I then go on to show that certain conditions do not hold, and the implications that it doesn't. 

### A model of store location: 
This is the first "theoretical" model I developed. I did it in Excel and I replicate it in R. The motivation comes for a request of how many, and which of the current stores to close. To develop this model, I instead asked myself in hindsigh: where would it be optimal to open the stores? I then created a simple algorithm that iteratively selected the best location for a store, which covered a 500 km radius where no other store should be opened. Then, a second store was opened in the best remaining possible locations. This process was repeated until all the area was covered. The result is a number of places where to have a store opened. Everything else can be closed. I discuss how it is then possible to calculate the distance to an optimal store location, and how this variable would predict a well performing store. I also discuss how stores were found to cluster around the predicted optimal store locations, and how the number of stores in the area can be thought of as a measure of inneficiency due to potential canibalism between the stores. In the specific case that motivated the project, this would have resulted in sales of "lower quality", that generated lower revenue, stayed for less time before churning, etc. 


