---
  title: "Professional Timeline"
---
#### --- Senior Market Intelligence Analyst at Claro: Jun 2012 - Sep 2015 (3 years, 3 months)
For my last formal experience in the Dominican Republic I work for Claro, a telecommunications company. It was originally a monopoly called CODETEL, it was purchased by Verizon in the year 2000 (I think...) and then by the America Movil group which is owned by Carlos Slim. Currently they offer all telecommunications services: Landlines, Fixed Internet, Mobile phone and internet, as well as TV. My experience here can be divided into two phases. 

##### *First Phase*:
At the beggining, I was in charge of supporting the market research efforts related to the Fixed Internet Line of Business. This included updating a number of monthly marketing KPI report for this Line of Business, a so called "Tracking Report". 

The company had a dedicated telephone survey team, and every month this team would spend a number of days collecting data according to a standard questionnaire. 

For this specific report, I had to verify the questionnaire was correct and make any necessary changes, and once the data was collected I would compute metrics such as Top of Mind, Aided and Unaided Brand Awareness, Advertising Awareness, Customer Satisfaction, among others. The results from that month would then populate the Excel and Power Point reports, which were sent to the Marketing and Product Development departments, as well as Upper Management (Directors, Vice Presidents and CEO). 

There were also specific requests made to do research on an ad-hoc basis. Again, I was assigned to the Fixed Internet LOB, and would consult Marketing and Product Owners of this LOB when they had research needs. I would meet with them, understand the problem they faced, and then transform their information needs into specific research objectives to be achieved using data collected from a telephone survey. 

##### *Second Phase*: 
The second phase coincided with me finishing a specialization in Statistics Applied to Business where I learned of Statistical Modelling and Econometrics. At this point my responsibilities shifted from updating KPIs and doing ad-hoc research, to doing research using econometric modelling. 

These projects required a lot more care and were aimed at answering strategic, rather tan tactical questions. As such, the time required to design them was significantly higher. Any given project required days of reviewing the literature in search of the appropiate method, which then needed to be properly understood. After deciding on the model, I would take over and design the research when using Surveys, or gathering the data from the internal database. Then would follow the estimation phase, along with a discussion on the results. Finally, the results would be presented to high management along with the implications and recommendations for action. 

This was the phase were I became aware of the importance of theory when doing empirical research. Without a theoretical framework guiding the design anything goes. For that reason, I decided to take my experiences and do a Masters of Science in Economic abroad; where I would be exposed to sufficiently advanced methods. 

#### --- Project Anayst at Dichter-Neira: Jun 2011 - May 2012 (1 year)

My second formal experience was in the role of Project Analyst at [Dichter-Neira Research Group](http://www.dichter-neira.com/), a Panama based agency present in several countries in Latin America. 

This company was bigger and also more structured. As such, the kind of role I played was more oriented at implementation, rather than to research design -- unlike with my previous experience. 

The company had created "templates" for several projects. This served the purpose of giving clients something specific to request; a project that would answer a specific information need. At the same time, this allows the company to minimize implementation costs. 

Once the project was approved, the research manager would use a template questionnaire and customize it to the specific project at hand. I would then take it and coordinate with a  specialized department to have it programmed into the PDAs (Portable Digital Assystants). I would go on to Pilot Test the questionnaire and make sure the digital logic was appropiately programmed.  

I would also coordinate with the operations department to verify they have everything they need and answer any questions about the questionnaire. 

In the meantime, while data collection was underway, I would create a first draft of the report containing all the analyses appropiate to the specific project which would allow to achieve the research objectives. 

After data collection was complete, I would request the specialized statistical analysis department to perform the necessary analysis with the data. They would do it, and provide me with a set of tables that I coudl use to populate the draft report and get a final version. 

The final stage involved reviewing the report with the Research Manager in preparation to present the findings to the client. 


#### --- Quantitative Analyst at MKT Global: Jun 2010 - Nov 2010 (6 months)

This was my first career job. The company, [MKT Global](http://mktglobal.com/), is a small Market Research Agency in Santo Domingo, Dominican Republic. I was not done with my Bachelor's in Marketing when I started, but I already knew that I wanted to guide my career towards marketing research. 

Since the company was quite small -- less than 10 full-time employees -- I was able to see the market research process in great detail. 

My role was that of Quantitative Analyst. I entered the project at the beggining and end of the market research process. 

In the beggining, when a project was approved, I received the Research Proposal specifying the research objectives. From there, I would design a questionnaire to achieve them. 

In the tail of the process, fter the survey team collected the data, I would perform the analyses I had envisioned in the beggining and create graphs and charts to answer the research questions in a Power POint presentation. 

At last, I would accompany the Manager or Director to meet with the client and present the results. My role there was as of support in case of questions, but sometimes I also did the presentation to the clients myself. 

